apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-v4
  namespace: default
spec:
  replicas: 2
  #minReadySeconds: 60
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: react-v4
  template:
    metadata:
      labels:
        app: react-v4
    spec:
      containers:
        - name: react-v4
          image: 243582926723.dkr.ecr.ap-northeast-2.amazonaws.com/react-v4:687536e1
          # 520d2d1a 헌거
          # 687536e1 새거
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 40"]