---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: getcommu-v1
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: getcommu-v1
  template:
    metadata:
      labels:
        app: getcommu-v1
    spec:
      containers:
        - name: getcommu-v1
          image: 243582926723.dkr.ecr.ap-northeast-2.amazonaws.com/getcommu-v1:e11280a6
          #e11280a6
          #e11280a6 새거
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: getcommu-v1
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/"
spec:
  selector:
    app: getcommu-v1
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80