---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-v4-stage
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-v4-stage
  template:
    metadata:
      labels:
        app: react-v4-stage
    spec:
      containers:
        - name: react-v4-stage
          image: 243582926723.dkr.ecr.ap-northeast-2.amazonaws.com/react-v4:f38504ff
          #92248c25
          #f38504ff 새거
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: react-v4-stage
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/"
spec:
  selector:
    app: react-v4-stage
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "frontend-ingress-stage"
  namespace: default
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "react-v4-stage"
                port:
                  number: 80